language: node_js
sudo: true
node_js:
  - "6"
  - "5"
  - "5.1"
  - "4.4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "iojs"
cache:
  directories:
    - node_modules
before_install:
  - npm install
script:
  - npm test
after_script:
  - npm run coverage
